FROM debian:latest

# Install any necessary libraries if they aren't included by default
RUN apt-get update && apt-get install -y \
    libstdc++6 \
    libgcc1 \
    libc6

COPY ./bin/tester ./app
RUN chmod +x ./app

CMD [ "./app" ]
