version: '3.8'

services:
  
  keydb:
    image: eqalpha/keydb:latest
    container_name: keydb
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - keydb-data:/data
    command: ["keydb-server", "/etc/keydb/keydb.conf"]

  s3mock:
    image: adobe/s3mock
    ports: 
      - 9090:9090
      - 9191:9191
    environment:
      initialBuckets: default
      root: /data
      retainFilesOnExit: true

volumes:
  keydb-data:
    driver: local

