apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.namePrefix }}-minio
  labels:
    app: {{ .Values.namePrefix }}-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.namePrefix }}-minio
  template:
    metadata:
      labels:
        app: {{ .Values.namePrefix }}-minio
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - {{ .Values.minio.preferredHostname }}
      containers:
        - name: minio
          image: minio/minio:latest
          command:
            - /bin/bash
            - -c
          args: 
            - minio server /data --console-address :9090
          ports:
            - containerPort: 9090
          resources:
{{ toYaml .Values.minio.resources | indent 12 }}
          volumeMounts:
            - mountPath: /data
              name: minio-data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: {{ .Values.namePrefix }}-minio 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namePrefix }}-minio-api
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30006
  selector:
    app: {{ .Values.namePrefix }}-minio
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namePrefix }}-minio-ui
spec:
  type: NodePort
  selector:
    app: {{ .Values.namePrefix }}-minio
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30005
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.namePrefix }}-minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minio.storageSize }}
