apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.namePrefix }}-tester
  labels:
    app: {{ .Values.namePrefix }}-tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.namePrefix }}-tester
  template:
    metadata:
      labels:
        app: {{ .Values.namePrefix }}-tester
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - {{ .Values.chdbTester.preferredHostname }}
      containers:
        - name: chdb-ex-tester
          image: pi0:30000/chdb-ex-tester 
          resources:
{{ toYaml $.Values.chdbTester.resources | indent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp-data
      volumes:
        - name: tmp-data
          emptyDir: {}
