namePrefix: "chdb"
preferredStorageHostname: pi0
preferredWorkerHostname: pi1
keyStore:
  resources:
    requests:
      memory: "512Mi"
      cpu: "1000m"
      ephemeral-storage: "1Gi"
    limits:
      memory: "512Mi"
      cpu: "1000m"
      ephemeral-storage: "1Gi"
minio:
  storageSize: "5Gi"
  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"
      ephemeral-storage: "1Gi"
    limits:
      memory: "1Gi"
      cpu: "1000m"
      ephemeral-storage: "1Gi"
chdbWorker:
  resources:
    requests:
      memory: "1Gi"
      cpu: "1000m"
      ephemeral-storage: "2Gi"
    limits:
      memory: "1Gi"
      cpu: "1024m"
      ephemeral-storage: "2Gi"

