namePrefix: "chdb"
keyStore:
  assignToNode: pi0
  resources:
    requests:
      memory: "512Mi"
      cpu: "1000m"
      ephemeral-storage: "1Gi"
    limits:
      memory: "512Mi"
      cpu: "1000m"
      ephemeral-storage: "1Gi"
minio:
  assignToNode: pi0
  storageSize: "10Gi"

